M48
; DRILL file {KiCad 7.0.1} date Thu Jan 11 23:21:17 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-11T23:21:17+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X4.7426Y-2.1612
X4.7426Y-2.3888
T2
X5.3937Y-2.1654
X5.3937Y-2.4016
T0
M30
